### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ccocks** [SpyC0der77/spycoder77.github.io#1]
@SpyC0der77, It seems that you have followed me, which means you are also following my work.

Do you want to join Rain, our organization? Or are you following for a different reason?
If you want more info about Rain, please ask.

**Comment by SpyC0der77** [comment]
I mean, i just followed u cuz you are helpful on scratchattach github

**Comment by ccocks** [comment]
Oh... I thought you liked my work... anyways, are you interested?

**Comment by SpyC0der77** [comment]
I honestly haven't looked at your work lol

On Thursday, Oct 17, 2024, 5:08 PM, wrote:

> Oh... I thought you liked my work... anyways, are you interested? You are
receiving this because you were mentioned.Message ID:

------------------------------
Best Regards,
Carter Stach

**Comment by SpyC0der77** [comment]
oh freak

**Comment by SpyC0der77** [comment]
thanks for letting me know

**Comment by SpyC0der77** [comment]
delete that file pls

**Comment by ccocks** [comment]
It's not a file. I just pasted it...

<sub>I wonder how many comments you've sent like this...</sub>

**Comment by SpyC0der77** [comment]
None other than that, I just forgot that time

**Comment by SpyC0der77** [comment]
When I respond by email I always remove my signature

**Comment by ccocks** [comment]
Oh....
